### ISSUE TITLE
Doesn't work with firefox 49

### ISSUE THREAD

**Issue by MeisterP** [swick/mozilla-gnome-keyring#44]
Forms don't get filled out any more. The message in the console is:
`GnomeKeyringLoginManagerStorage: Called ([object XPCOutParam],[xpconnect wrapped nsIPropertyBag])`

The passwords and sites are still accessible in Preferences -> Security -> Saved Logins

**Comment by MeisterP** [comment]
Albeit concerning another extension, https://github.com/jfitzell/mozilla-keychain/issues/83 might be related.

**Comment by theOtherNuvanda** [comment]
Same here.

**Comment by swick** [comment]
Fixed in 40d6f25851847605390ecb490dd547b8844a7764. Uploaded version 0.12 to addons.mozilla.org.

**Comment by MeisterP** [comment]
Thanks a lot for the quick fix. Much appreciated :-)

**Comment by theOtherNuvanda** [comment]
That was quick. Thank you!

**Comment by eighthave** [comment]
thanks for the quick update!  I can't find with my Firefox v49 on Ubuntu 14.04.  The add-on page is still showing 0.11:
https://addons.mozilla.org/en-US/firefox/addon/mozilla-gnome-keyring/

**Comment by eighthave** [comment]
also, the git tags for 0.11 and 0.12 are missing from github

**Comment by mratmartinez** [comment]
Yes. It seem that it wasn't updated it in the site yet.

**Comment by swick** [comment]
The new version was uploaded directly after pushing the changes. Still in review queue:

> Hello,
> Your add-on, GNOME Keyring integration 0.12, has been flagged for Admin Review.
> Your add-on is still in our review queue, but it will need to be checked by one of our admin reviewers. This means that your review will probably take longer than usual.
